### ISSUE TITLE
Parsing CSV files of certain arbitrary lengths suddenly stops

### ISSUE THREAD

**Issue by maxharlow** [signicode/scramjet#102]
Hi, me again, sorry. I'm seeing a problem where `CSVParse` seems to fail on some CSV files. I've been trying different things to try and work out what the common theme is -- and it appears to be something to do with the length (or size?) of the file.

I've written some example code which replicates the issue:

```js
const FS = require('fs')
const FSP = require('fs/promises')
const Scramjet = require('scramjet')

async function run(n) {
    console.log(`Try: ${n}`)

    const rows = Array.from(new Array(n).keys()).map(i => `x,${i}`).join('\n')
    await FSP.writeFile('example.csv', rows)

    const x = await Scramjet.StringStream.from(FS.createReadStream('example.csv'))
        .CSVParse()
        .reduce(a => a + 1, 0)

    console.log(`Got: ${x}\n`)
}

async function loop() {
    let n = 1
    while (true) await run(n++)
}

loop()
```

I would expect this to just run forever, but actually it stops when `n` reaches 17. If I set `n` to 18 it stops again at 55. After that, 78. It's really odd.

If I replace `.CSVParse()` with `.lines()`, it works as expected, so it does seem to be something to do with CSV parsing.

I'm using Scramjet v4.35.10 and Node v15.6.0.

**Comment by maxharlow** [comment]
Just to add -- when this happens there's no `end` event

**Comment by MichalCz** [comment]
Ok, this seems a bit odd - seems that CSVParse doesn't work in this scenario, which is very strange.

Initial tests show that this is not caused by `reduce`. I'll keep digging.

**Comment by MichalCz** [comment]
@maxharlow I'm still looking at this, but I think it may be connected the previous issue you reported...

**Comment by maxharlow** [comment]
@MichalCz Excellent, thanks for taking a look!

**Comment by MichalCz** [comment]
Ok, so it seems that anything over 16 items in a single return value to `flatten` which is used by `CSVParse` is actually halting.

I found the issue and a fix, but I need to take a look at the async version of flatten as this doesn't seem to keep order.

**Comment by MichalCz** [comment]
Ok, seems to work in the latest version, please confirm.

**Comment by maxharlow** [comment]
Yes, it seems to work -- thanks for the fix!
