### ISSUE TITLE
PostgreSQL doesn't like scramjet

### ISSUE THREAD

**Issue by Extarys** [signicode/scramjet#16]
I have multiple CSV files that I'd like to import in PostgreSQL. Here is my code:

```javascript
async function insert_countries() {
  return new Promise(async function(resolve, reject) {
    const { StringStream } = require('scramjet')
    const fs = require('fs')
    const path = require('path')

    const INSERT_ENTRY =
      'INSERT INTO countries (iso3, iso2, name, dialing_code, dialing_exit, population, area_km2) VALUES ($1, $2, $3, $4, $5, $6, $7);'
    StringStream.from(
      fs.createReadStream(
        'countries.csv'
      )
    )
      .lines()
      .parse(line => {
        // Each line need to be properly formated
        const entry = line.split(',') //comma split

        let reconstruction = []

        // country,country_code,external,iso2,iso3,population,area_km2

        /*       iso3	character varying(3) PRIMARY KEY,
        iso2	character varying(2),
        name	TEXT NOT NULL,
        dialing_code character varying(5),
        dialing_exit character varying(8)
        */
        // The following fields need formating
        reconstruction.push(entry[4])
        reconstruction.push(entry[3])
        reconstruction.push(entry[0])
        reconstruction.push(entry[1])
        reconstruction.push(entry[2])
        reconstruction.push(parseInt(entry[5]))
        reconstruction.push(parseInt(entry[6]))
        console.log(reconstruction)
        return reconstruction
      })
      .setOptions({ maxParallel: 1 }) // FIXME: Testing only
      .each(async reconstruction => {
        const client = await this.pg.connect()
        try {
          await client.query(INSERT_ENTRY, reconstruction)
        } catch (err) {
          console.log('Error while adding line...', err)
        } finally {
          client.release()
        }
      })
      .run()
      .then(
        () => {
          console.log('Read entire file.')
          return resolve(true)
        },
        e => console.log('Error while handling file.', err)
      )
  })
}
```

If I comment out the postgresql part where the insert happen, the CSV is read to the end. But with postgresql I see the vague `[nodemon] app crashed - waiting for file changes before starting...`

Is there an option of some kind I should be aware of or some limitation to make this compatible ?

**Comment by MichalCz** [comment]
Hi,

I don't think this may be due to incompatibility of some sort (and privately I can tell you that scramjet loves postgres - maybe they just have a slightly worse day ;) ).

I'll check your code a little later and get back to you.

**Comment by MichalCz** [comment]
@Extarys, would you be so kind and add this line in `each` and post the output here:

```javascript
console.log('arg:', reconstruction);
// next comes: const client = await this.pg.connect()
```

Looking at your second question I think this may be due to attempting to save `NaN`, but I'm unsure why you don't see an error there.

**Comment by Extarys** [comment]
@MichalCz :stuck_out_tongue_closed_eyes: maybe you're righ.
```
arg: [ 'AFG', 'AF', 'Afghanistan', '93', '00', 29121286, 647500 ]
arg: [ 'ALB', 'AL', 'Albania', '355', '00', 2986952, 28748 ]
[nodemon] app crashed - waiting for file changes before starting...
```

I'm still testing on my side if it's a human error or if it's postgres that "cannot handle" ti or whatever.

**Comment by MichalCz** [comment]
I'm not sure if this was your question or not, but very similar [question about writing geo data to postgres](https://stackoverflow.com/a/52995931/3790725) is there.

Please leave this issue open, as I would expect that your code would need to show some message...

Now if you could do another thing (or two)? 

* if the `pg` property is a pool, can you use `pool..query` method directly instead of creating the client and releasing it?
* can you surround the whole `each` callback with another `try...catch` (leave the current one inside).

If you can get an error message like that I'd see it looked into, why the errors are not caught in your case.

**Comment by Extarys** [comment]
Those are actually great ideas. Annnnd, I'm the dude from the SO question in fact. :stuck_out_tongue: 
`const client = await this.pg.connect()` is already a pool, using fastify-pg plugin. I just looked at the source code to make sure it was returning a pool.

I finally got it working by defining postgres connection at the beginning and I removed the Promise for now for testing.

For future reference, `that` is the fastify object comming from the route:

```
createDb: async function(req, reply) {
    await insert_countries(this)
}
```

Code:
```
async function insert_countries(that) {
  const { StringStream } = require('scramjet')
  const fs = require('fs')
  const path = require('path')

  const client = await that.pg.connect()
  console.log(client ? true : false)

  const INSERT_ENTRY =
    'INSERT INTO countries (iso3, iso2, name, dialing_code, dialing_exit, population, area_km2) VALUES ($1, $2, $3, $4, $5, $6, $7);'

  StringStream.from(
    fs.createReadStream(
      'countries.csv'
    )
  )
    .lines()
    .parse(line => {
      // Each line need to be properly formated
      const entry = line.split(',') //comma split

      let reconstruction = []

      // The following fields need formating
      reconstruction.push(entry[4])
      reconstruction.push(entry[3])
      reconstruction.push(entry[0])
      reconstruction.push(entry[1])
      reconstruction.push(entry[2])
      reconstruction.push(parseInt(entry[5]))
      reconstruction.push(parseInt(entry[6]))
      return reconstruction
    })
    .setOptions({ maxParallel: 1 })
    .each(async reconstruction => {
      console.log('arg:', reconstruction)

      try {
        await client.query(INSERT_ENTRY, reconstruction)
      } catch (err) {
        console.log('Error while adding line...', err)
        // some more logic could be here?
      } finally {
        // client.release()
      }
    })
    .run()
    .then(
      () => {
        console.log('Read entire file.')
        // return resolve(true)
        client.release()
      },
      e => console.log('Error while handling file.', err)
    )
}
```

So my guess is in fact it was connecting and disconnecting from the pool every time. thanks for your patience, Scramjet is very nice and powerful, I'm gonna play around it :smile_cat:
