### ISSUE TITLE
CSVParse() and batch() seem not to work anymore

### ISSUE THREAD

**Issue by SqueezedLight** [signicode/scramjet#2]
Hi,
first of all, thanks for this great library. Worked absolutely great up to now!

We use the following code:
```
fileStream.pipe(new StringStream('utf-8'))
      .CSVParse({
        skipEmptyLines: true,
        header: true,
      })
      .batch(500)
      .map((items) => {
        console.log(items);
       });
```

It seems `batch` and `CSVParse` do not work together anymore. If we remove `batch` the `console.log` is called. If not, no error occurs, but the `console.log` statement within the `map` is never executed. Any ideas? I checked the last commits, but couldn't find anything suspicious.

Thanks in advance

**Comment by MichalCz** [comment]
It may be connected to a couple changes in pause/resume and around each... I'll check.

**Comment by MichalCz** [comment]
Confirmed - the issue seems to be introduced in 4.10 with the `into` method which seem to:

1. not forward errors
2. not end the stream

The new method was used to improve `remap`, `flatMap` and `flatten` methods.

**Comment by MichalCz** [comment]
Please update to v4.12.3 - published in npm.

If you be so kind, please also confirm the fix.

**Comment by SqueezedLight** [comment]
Wow, that one was quick! It works again.
Thank you very much!

**Comment by SqueezedLight** [comment]
@MichalCz it seems the issue happens again. Same behaviour. With `batch()` it doesn't work, without `batch` it works.
Do you have any clue, why this happens again?

Thanks a lot!

**Comment by MichalCz** [comment]
Hi @SqueezedLight.

Which version do you have currently installed?

Also we may need to drill into your use case with batch, the current `batch` mtehod  is tested in two cases:

* [Synchronous batch](https://github.com/signicode/scramjet/blob/master/samples/data-stream-batch.js#L12) where the data is available more or less upfront.
* [Asynchronous batch](https://github.com/signicode/scramjet/blob/master/samples/data-stream-batch.js#L30) where the data is generated in an async process.

So what should I do to include your case here? Perhaps you could isolate your code and reproduce the error somehow?

**Comment by SqueezedLight** [comment]
Hi @MichalCz,
i currently use v4.18.12.

I use it asynchronously (read a file stream from a csv on disk).
```
const fileStream = fs.createReadStream(fullPath);

fileStream.pipe(new scramjet.StringStream('utf-8'))
      .CSVParse({
        skipEmptyLines: true,
        header: true,
      })
      .batch(500)
      .map((items) => {
        const options = {...};

        new CsvJob({ options, items }, req.session.id);
        return null;
      });
```

I will try to investigate more.

**Comment by MichalCz** [comment]
How many lines are in the file btw?

**Comment by MichalCz** [comment]
...and... perhaps you could add the following lines at the end of your pipeline?

```javascript
.run()
.catch(e => console.error(e))
```

And, if that works I'll share the "why's"

**Comment by SqueezedLight** [comment]
less than 500.  I tried with multiple file between 70-200 lines

**Comment by SqueezedLight** [comment]
Like this?

```
const fileStream = fs.createReadStream(fullPath);

fileStream.pipe(new scramjet.StringStream('utf-8'))
      .CSVParse({
        skipEmptyLines: true,
        header: true,
      })
      .batch(500)
      .map((items) => {
        const options = {...};

        new CsvJob({ options, items }, req.session.id);
        return null;
      })
      .run()
      .catch(e => console.error(e));
```

Seems not to change the behaviour...

**Comment by MichalCz** [comment]
Ok. Confirmed. I would say that once again the last batch does not get emitted...

**Comment by MichalCz** [comment]
Ok. It seems that your case uses two flush functions that get overwritten and they supposed to get chained.

Please expect a fix approximately on Monday.

In mean time, try to add `.tap()` after CSVParse as a workaround.

**Comment by SqueezedLight** [comment]
That would be brilliant! Thanks a lot!

Btw, `.tap()` seems to have no effect...

**Comment by SqueezedLight** [comment]
Hi @MichalCz any update on this one? If you don't find time, would you elaborate a little on fixing the bug? I can try to contribute a bug fix.

**Comment by MichalCz** [comment]
Hi,

Please test with a new version. I did include your specific case in the test scenarios (see `samples/data-stream-batch.js`).

I'd be happy for a contribution, but I'm starting work on version 5.0.0 so help and testing of that would be very helpful. :)

**Comment by SqueezedLight** [comment]
YES! This one works!
Thank you so much. I will try to help/test where i can ;) I guess we can close here again.

**Comment by MichalCz** [comment]
And hopefully with that test - for the last time. :)

**Comment by KwangGan** [comment]
Hi Thanks for great library. 

but this issue happened again with some strange scenario 

I have to function like this but this one stall at first .batch() no error no return just process timeout

` res.setHeader('Content-Type', 'application/json; charset=utf-8')
            StringStream
              .from(async function* () {
                const response = await axios.get(csv_url, {
                  responseType: 'stream'
                })
                yield* response.data.pipe(await stripBomStream())
              }, { maxParallel: 4 })
              .CSVParse({ skipEmptyLines: true, header: true })
              .filter((item: any) => (item.Class_Id && parseInt(item.Class_Id) !== 0 && item.Class_Discount > 0))
              .map(async (item: any) => {
                
                const master_name = master_subgroup.find(
                  (master_item: any) => (parseInt(master_item.id) === parseInt(item.Class_Id)))
              
                if (!master_name.name || master_name.name === "") return {}
                all_data_count++
                batch_data_count++
                console.log("pass 3")
                const class_obj = {
                  id: item.Class_Id,
                  name: master_name.name,
                  discount_rate: parseFloat(item.Class_Discount),
                  parent_id: master_name.parent_id,
                  status: "active"
                }
            
             
                return class_obj

              })
              .batch(500)  < process Stalled here
              .map(async (items: any) => {
                console.log("All Items is : " + items.length)
                const start_at = (batch_count * round_count) + 1
                round_count += 1
                const end_at = (start_at + items.length) - 1
                const range = start_at + "-" + end_at

                const unique_items = discount.objectToArray(discount.arrayToObject(items, "id"))
                const complete_subgroup = unique_items.filter((item: any) => {
                  return Object.keys(item).length > 0
                })
                console.log("Master group is : " + JSON.stringify(complete_subgroup))

            
                if (complete_subgroup.length > 0) {
                  const discount_obj = { subgroup: complete_subgroup }
                  console.log(discount_obj)
                  console.log("before send")
                  const update_result = await discount.update(req.params.uid, discount_obj)

             
                  console.log("before result")
                  console.log(update_result.success)
                  console.log("before return")
                  if (update_result.success) {
                    return JSON.stringify({
                      rows: range,
                      received: items.length,
                      accepted: unique_items.length - 1,
                      status: "import_successful",
                      message: "ข้อมูลได้รับการบันทึกแล้ว"
                    }
                    )
                  } else {
                    return JSON.stringify({
                      rows: range,
                      received: items.length,
                      accepted: 0,
                      status: "problem_with_database",
                      message: "ไม่สามารถบันทึกข้อมูล ช่วงข้อมูลที่: " + range,
                    })
                  }
                } else {
                  return JSON.stringify({
                    rows: range,
                    received: items.length,
                    accepted: 0,
                    status: "data_id_not_exits",
                    message: "ช่วงข้อมูลที่: " + range + " รหัสไม่มีอยู่จริงในระบบ ",
                  })
                }
              })
              .catch((error: any) => {
                console.log("catch block 1" + error.stack)
                if (error.code === "ERR_SCRAMJET_EXTERNAL") {
                  res.statusCode = error.cause.response.status
                  const error_obj = makeErr("can_not_reach_product_api",
                    "ไม่สามารถติดต่อ Product API ได้ กรุณาตรวจสอบ",
                    error.cause.response.status,
                    process.env.PRODUCT_API_URL)
                  res.send(JSON.stringify(error_obj))
                  return
                } else {
                  res.statusCode = 422
                  const error_obj = makeErr(error.code, error.message, 422)
                  res.send(JSON.stringify(error_obj))
                  return
                  //  return JSON.stringify(error_obj)
                }
              })
              .batch(10000)
              .stringify((resp: any) => {
                // console.log(resp)
                res.statusCode = 200
                return "[" + resp + "]"
              })
              .catch((error: any) => {
                console.log("catch block 3")
                if (error.code === "ERR_SCRAMJET_EXTERNAL") {
                  res.statusCode = error.cause.response.status
                  const error_obj = makeErr(error.cause.response.data.code,
                    error.cause.response.data.message,
                    error.cause.response.status)
                  //res.send(JSON.stringify(error_obj))
                  return JSON.stringify(error_obj)
                } else {
                  res.statusCode = 500
                  const error_obj = makeErr(error.code, error.message, 500)
                  // res.send(JSON.stringify(error_obj))
                  return JSON.stringify(error_obj)
                }
              })
              .toStringStream()
              .pipe(res)`

**Comment by MichalCz** [comment]
Hi @KwangGan please subscribe to #57 I'll be working on your report there...
