### ISSUE TITLE
Use and Learn Immutable Data Structures to gain Performance

### ISSUE THREAD

**Issue by frank-dspeed** [signicode/scramjet#29]
https://facebook.github.io/immutable-js/

**Comment by MichalCz** [comment]
@frank-dspeed I'm well aware of Immutable.js, but please note that Scramjet has very little dependencies and is called lightweight for that reason also. We have tried to avoid mutation in the code and I can't think of many places that much mutation is done at run time (a couple of arrays keeping an incremental list).

Please point to specific places you think need improvement, my team will look into this. We also need some kind of measurement around that so please propose some kind of a benchmark on that.

**Comment by frank-dspeed** [comment]
@MichalCz biggest improvement that i see is avoid forking of nodejs processes that are consuming round about 50mb of memory each :)

**Comment by MichalCz** [comment]
We were initially looking into the memory issue on threads and other thread implementations, but came to conclusion that we'd rather wait for Worker Threads in v11. Other solutions include a low memory version of node, but that requires bundling binaries which I'd prefer to avoid.

Worker threads are our current candidate, but it's not yet implemented as we aim for a release of such closer to the release of next LTS (probably with some pre-release).

And if I may, this doesn't have much to do with Immutable.

**Comment by frank-dspeed** [comment]
@MichalCz biggest improvement that i see is avoid forking of nodejs processes that are consuming round about 50mb of memory each :)

**Comment by MichalCz** [comment]
@frank-dspeed can you clarify one bit.

From the documentation did you understand that scramjet is always multi-threaded? 

Because it's actually the other way round, you need to want to use multi-threading. I'm getting a similar question somewhere else and I guess we should redo the intro a little to make this clear.

**Comment by frank-dspeed** [comment]
@MichalCz its clear! but this is not a good idea on many systems and also not a good idea for many tasks you should consider making this optional so it can be disabled on LowRam Systems or Systems that use own Algo for archiving that.

Example when i want to code a performant NodeJS Application i Code it always for a Single TH then i start it as often as i need it and cluster it via iptables routing this outperforms all alternatives.
