### ISSUE TITLE
DataStream.slice(0) does not conform to documented or tested behavior

### ISSUE THREAD

**Issue by jamesearl** [signicode/scramjet#30]
**Basics**
The documentation for DataStream.slice reads

>Returns a stream consisting of an array of items with 0 to start omitted and length items after start included. Works similarily to Array.prototype.slice.

However the test cases and code do not reflect the fact that a call to `slice()` or `slice(0, x)` does not behave as expected.

**To Reproduce**
Both of the following tests demonstrate what I'm talking about:
```
DataStream.fromArray([1,2,3,4,5,6,7,8,9,0])
            .slice()
            .toArray()
            .then(arr => {
                test.deepEqual(arr, [1,2,3,4,5,6,7,8,9,0], "Shifted items should be same as starting items");
            });

DataStream.fromArray([1,2,3,4,5,6,7,8,9,0])
            .slice(0,3)
            .toArray()
            .then(arr => {
                test.deepEqual(arr, [1, 2, 3], "Shifted items should be starting with first element");
            })
```

I'll open a PR with additional tests demonstrating these.

**System:**
 - OS: Ubuntu Desktop 16.04
 - Node version: 10.11.0
 - Scramjet Version: 4.20.3, 4fb50f557de995c39c6400f79c288e1d791c560a

**Comment by MichalCz** [comment]
Hey, nice work. I'll take a look at this over the weekend.

**Comment by jamesearl** [comment]
Thanks! I tried fixing it myself, but it's going to take me a little while to get familiar with the codebase. I'll add more details if I make any progress.

**Comment by MichalCz** [comment]
I found a fix for this. I'll commit this today and release a new version.
