### ISSUE TITLE
how can I pipe to regular node transformStream with a scramjet workflow?

### ISSUE THREAD

**Issue by leftcoastgeek** [signicode/scramjet#42]
Hi I have some code that looks like this.
```js
async function server() {
  return await (StringStream.from(getCredential()) // create a DataStream
  .JSONParse()
  .map((res) => res.accessToken)
  .map(getWS) //getWS returns a `websocket-stream` 
  .do(onmessageSubscribeQuote))
  .pipe(myNodeTransFormStream)
}
server()
```
the call to pipe always breaks with a  `UnhandledPromiseRejectionWarning: Error: The "chunk" argument must be one of type string or Buffer.` what am I missing?

**Comment by MichalCz** [comment]
Hi,

It seems that your TransformStream is not in object mode. You'd need to use `stringify` or `toBufferStream` after `do`, so you can safely pass that to a bit stream. You can also use object mode stream in transform, look it up in node.js stream docs - if you can't find it, let me know.

The cause for this would be that scramjet works on objects by default - so it's a stream of `{}`. Node streams, unless told to, work on strings or buffers, so streams of `""`.

Let me know if this helped.

**Comment by MichalCz** [comment]
Hi @leftcoastgeek - have you checked the above perhaps?
