### ISSUE TITLE
Functions have inappropriate type for optional parameters in TypeScript declaration

### ISSUE THREAD

**Issue by Sardtok** [signicode/scramjet#44]
**Basics**
TypeScript declarations do not allow not leaving out optional parameters.

**Describe the bug**
In the TypeScript declarations optional parameters do not have types with ?, making them required parameters. Examples include `toArray(initial: any[]): any[];`, where initial is described as an optional argument. However, this should be `toArray(initial?: any[]): any[];`. This also goes for DataStream.map functions, which take an optional sub-class constructor.

**To Reproduce**
Attempt using the functions without supplying optional parameters in TypeScript. This should produce errors during transpilation.

**Expected behavior**
Use functions without supplying optional parameters. Compilation should not produce errors.

**Test case**
If possible, please provide an automated test case to include, better yet in a forked scramjet repo in `test/cases`.

**Screenshots**
Not applicable

**System:**
- Any OS
- TypeScript 3.4.1

**Additional context**
Not applicable

**Comment by MichalCz** [comment]
Hey, thanks for reporting this... I'll take a look and report back on my findings...

**Comment by MichalCz** [comment]
Hi @Sardtok can you check version v4.23 and report back on the issue?

**Comment by Sardtok** [comment]
We've updated the dependencies, and it works perfectly.
Thanks for the super quick response!
