### ISSUE TITLE
XMLParse()

### ISSUE THREAD

**Issue by JurgenJocubeit** [signicode/scramjet#65]
Any chance you'll be including XMLParse() functionality?

**Comment by MichalCz** [comment]
I did think about this on a couple occasions - any proposals regarding a good streaming xml parser module that wouldn't include dependency weight that would incur relativistic effects? ;)

**Comment by JurgenJocubeit** [comment]
[fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) seems to be the favourite, but it's a not a streaming parser.

[xml-flow](https://www.npmjs.com/package/xml-flow) looks ok - I've never used it though. Uses the sax library. Also has a BSD license - not sure if this is a concern for you.

[xml-streamer](https://www.npmjs.com/package/xml-streamer) is based on node-expat and It implements the Node.js stream.Transform API. Not sure you want to add node-expat and lodash as dependencies though.

[muxml](https://www.npmjs.com/package/muxml) is a Node.js transform stream, is written with ES6, has a dependency on sax and is MIT licensed. I'm liking the look of this one.

So maybe the last one? ;-)

**Comment by MichalCz** [comment]
Looking at the options I'd just go and use `sax` as a dependency, as this would carry less weight...

Ok, the last time I inspected this I thought be best way would be to use `xpath` or `queryselector` as the argument for the data and I don't see anything that could solve this for us - which would mean sadly a new project (cool!). My idea would then be:

1. create a `sax` derived module that would do `readable -> sax -> xpath -> readable stream`
2. integrate that into `scramjet`.

Are you willing to help?

**Comment by JurgenJocubeit** [comment]
I'm willing to help, not sure how much help I can be though... I come from the C# and ruby worlds, node and javascript are still are still on my learning curve. I'm using typescript, node and dart on a daily basis though, and I'm a fast learner. Just let me know what you would like me to tackle and I'll take a stab.

By new project do you mean a new module that could then be used by scramjet, or do you mean a plugin for scramjet?

**Comment by MichalCz** [comment]
Good, so:

1. No, I think the XMLParse should not be a plugin especially since CSVParse isn't. I'd start a separate repo just for the sax based streamed parser and use it as a dependency (so that's where your help would be appreciated).

2. XPath and Selectors could be both supported - we'd just need to see which ones are supported by sax and other tools we could setup. I'm in a process of setting up slack for Scramjet - I'll invite you as soon as we get going.

3. Yes, "xpath-like filter", that's the idea I have, a bit like the `JSONStream` module that I use for JSONParse method.

**Comment by JurgenJocubeit** [comment]
OK, let me know when you have slack setup, in the mean time I'll familiarise myself with ScramJet, JSONParse etc.

**Comment by MichalCz** [comment]
There's a discussion on the [**just opened scramjet slack**](https://join.slack.com/t/scramjetframework/shared_invite/enQtODg2MDIyMTQ5MzUxLTVlNTIwMmFlYWU0YTg2ZTg1YmFiOTZkZTdhNzNmNjE2ZmQ3ZWQzZjI5MGQyZDAyOWM2NDc5YzdmZGQzNGI3YTU) about this...

I think this could be the good way to work with this.

```javascript
const flow = require("xml-flow");
const {DataStream} = require("scramjet");
DataStream.from(function() {
    const xml = flow('./path/to.xml')
    const out = new DataStream();
    xml.on("tag:mytag", data => out.write(data));
    out.on("pause", () => xml.pause())
    out.on("resume", () => xml.resume())
    return out;
})  
    .each(console.log)
    .catch(e => {
        console.error(e.stack);
        process.exit(1);
    });
```
