### ISSUE TITLE
[Help Wanted] Typescript testing

### ISSUE THREAD

**Issue by MichalCz** [signicode/scramjet#89]
**Is your feature request related to a problem? Please describe.**

Every now and then a change in `scramjet` breaks the typescript compatibility. How can we check if the `ts.d` files are ok?

**Describe the solution you'd like**

There should be a `npm run test:typescript-definitions` that should at least install scramjet as a dependency from a `file://` location and try to `tsc` a sample `ts` file.

Any ideas appreciated. PR's also.

**Comment by chapmanjacobd** [comment]
https://stackoverflow.com/questions/49296151/how-to-write-tests-for-typescript-typing-definition

https://github.com/ai/check-dts

**Comment by MichalCz** [comment]
Ok, that's quite interesting. :)

I included this in the flow - it seems to cover errors quite nicely. :)
