### ISSUE TITLE
Update example on home page now that request is deprecated?

### ISSUE THREAD

**Issue by gregmsanderson** [signicode/scramjet#91]
Hello,

I came across this project and tried the first example shown using StringStream which seems to work great.

_However_ it seems the request package is deprecated. Maybe update the example to instead use axios, fetch etc?

`request("https://api.example.org/v1/shows/list")`

Thanks!

**Comment by MichalCz** [comment]
Yeah, I guess we should change it, preferably to something light...

>
I guess node-fetch would be best? Axios seems quite heavy?

**Comment by gregmsanderson** [comment]
node-fetch seems the smallest, from https://github.com/request/request/issues/3143 so if it does the same, sure, swap for that?

**Comment by MichalCz** [comment]
Yeah. I'll review the dependencies in examples too - I think there's some `request` mentions in other places.

`fetch` is already on [www.scramjet.org](https://www.scramjet.org) - so I guess that's easiest to push some simple one liner to get the stream like:

`StringStream.from(async () => (await fetch('https://example.org/some.csv')).body)`

I'd need to test it first though...

**Comment by MichalCz** [comment]
Done and pushed. :)

Oh and at the same time, now this will work:

```js
Scramjet.from(fetch('https://www.example.net/some/resource.txt'))
```

A small addition. 😄
