### ISSUE TITLE
What is the best way to handle errors?

### ISSUE THREAD

**Issue by KrishnaPG** [signicode/scramjet#95]
Looking for help with handling the errors in the right way. Could not find much details in the documentation or examples, and my initial attempts at `reject` or `throw` does not seem to work.

Scenario: 

1. A large CSV file comes for processing and we need to ensure that it is of right "type" (i.e. the headers are as expected by the pipeline)
    - this is to ensure we do not end up injecting wrong kind of data into the DB from wrong csv "type". 
    - which means we need to fail fast and fail early for wrong types of files

Tried `throw` and `Promise.reject()`, but not seems to be stopping / aborting the pipeline. The records kept coming at it.
````
  DataStream.from(FastCSV.parseStream(s3Stream, csvOptions))
    .remap((emitFn, row) => {

        // if required columns do not exist, just abort the pipeline
        if (!row.ID || !row.date) 
            throw ErrorNoRetry(`Unable to find the required columns - probably wrong CSV type`);

        // ... probably a valid csv file type, do further work
    })   
````

2. Some error happens in the processing function somewhere down in the pipeline and we need to `abort` the whole stream from processing any further.
    - For example, the output file is not writable, or the destination DB is not available currently (or goes offline in the middle). In these cases instead of keep reading any further input data and keep processing it only to fail at the output stage, we need to abort (stop) the whole pipeline and let the user try after some time (restart/resume the whole pipeline fresh later).

**Questions**:

1. How to abort the pipeline safely from inside **any** function in the pipeline?
2. What is the best way to handle input validation errors? For example, check the headers of the CSV and **abort** if they are not matching. This should happen at the earliest point before large chunks are downloaded from the input stream. Not sure, how though.

**Comment by MichalCz** [comment]
Ok, so first of all check this: [DataStream..catch](https://scramjet.org/docs/data-stream#module_scramjet.DataStream+catch) - you can add this at any point in the stream and it works by catching any error that appears above it in the pipeline.

It should work for any function (sync or async) and it will be forwarded between steps.

If you want to raise an error from the outside that you can by using `raise`, but throwing and returning a rejected promise will help as well.

As to the above check - remap adds a review of the whole stream - perhaps it would be better to use `peek` and throw the error there.

```js
DataStream.from(FastCSV.parseStream(s3Stream, csvOptions))
    .peek((1, row) => {

        // if required columns do not exist, just abort the pipeline
        if (!row.ID || !row.date) 
            throw ErrorNoRetry(`Unable to find the required columns - probably wrong CSV type`);

    })
    .do(someOtherStuffFunction)
    .catch(e => {
       if (e instanceof ErrorNoRetry) {
           process.exitCode = 10; // or something - close connections and so on
       }
       return Promise.reject(e);
    })
```

In your case though I'd actually think of getting the csv fetching errors handled in the `from` function - take a look the [post about stream generators](https://scramjet.org/posts/generators). You can retry and actually solve #94 in one go.
