### ISSUE TITLE
DataStreamOptions.objectMode causes compilation failure

### ISSUE THREAD

**Issue by skif48** [signicode/scramjet#97]
![screenshot-2020-12-03T16:42:40](https://user-images.githubusercontent.com/6445180/101043091-9795d180-3586-11eb-8bbf-8b6549429f58.png)
Hi! I found a weird thing in types of this project.

**Basics**
DataStreamOptions interface. "objectMode" property.

**Describe the bug**
"objectMode" property is duplicated, which fails the compilation step.

**To Reproduce**
Just install scramjet@4.35.7 on a typescript project and try to compile it.

**Expected behavior**
No compilation error.

**Test case**
Just install scramjet@4.35.7 on a typescript project and try to compile it.

**System:**
 - OS: Ubuntu 18.04
 - Node version: 14.4.0
 - TypeScript version: 3.9.7
 - Scramjet Version: 4.35.7

Additional context:
https://github.com/signicode/scramjet/blob/master/.d.ts/index.d.ts#L980
https://github.com/signicode/scramjet/blob/master/.d.ts/index.d.ts#L992

Duplicated "objectMode" property seems to be added in this commit: https://github.com/signicode/scramjet/commit/5217af78632d758e1d49b774001f34efeecff6e7

Hope you can help, thanks!

Edit: attached a screenshot.

**Comment by MichalCz** [comment]
Thanks for the info. We'll fix this before Monday.

M.

**Comment by MichalCz** [comment]
And fix released - please reopen if you still experience any issues.

**Comment by skif48** [comment]
Hi @MichalCz !

Confirming, works now. Appreciate your help and quick resolution.

**Comment by MichalCz** [comment]
Well paraphrasing Monty Python... it's all in the days work for scramjet repair man. ;D
